############################## 
#Database connection config
##############################

spring:
  application:
    name: Media-stream-Ad
  datasource:
    url: jdbc:mysql://localhost/media-stream?serverTimezone=America/Chicago
    username: admin
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver
    
##############################  
  #Hibernate config
##############################  
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect    
    
    
    